server:
  port: 8082
spring:
  # 邮件配置
  mail:
    default-encoding: utf-8               # 编码格式
    host:                    # 邮件服务器地址
    protocol: smtp                        # 协议
    password:             # 授权码
    username:     # 邮箱地址
    port: 25                              # 端口（因邮箱而异）

  # rabbitmq配置
  rabbitmq:
    username:                # 用户名
    password:                # 密码
    host: 127.0.0.1               # 服务器地址
    port: 5672                    # 端口
    listener:
      simple:
        acknowledge-mode: manual  # 开启手动确认

  # redis配置
  redis:
    timeout: 10000ms        # 连接超时时间
    host: 127.0.0.1         # Redis服务器地址
    port: 6379              # Redis服务器端口
    database: 0             # 选择哪个库，默认0库
    lettuce:
      pool:
        max-active: 1024    # 最大连接数，默认 8
        max-wait: 10000ms   # 最大连接阻塞等待时间，单位毫秒，默认 -1
        max-idle: 200       # 最大空闲连接，默认 8
        min-idle: 5         # 最小空闲连接，默认 0
    password: 
